### ISSUE TITLE
Modal is not closed when register a new book successfully

### ISSUE THREAD

**Issue by acgtwentyone** [acgtwentyone/booktracks#46]
**Describe the bug**
Sometime the modal does not close, and even the success message is not displayed to the end user

**To Reproduce**
1. Go to Books page
2. Click on + button
3. Fill the title and author and then click on "Add Book"
4. See, the book is saved but no message displayed, and the modal does not automatically hide

**Expected behavior**
When a user successfully added a book the modal should hide and the application should display a message saying "Book 'title' added"

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android
 - Version: 10

**Comment by brandon-gs** [comment]
Hey, can I solve the bug?

**Comment by acgtwentyone** [comment]
Of course.

**Comment by acgtwentyone** [comment]
This issue is fixed by #50
