### ISSUE TITLE
Cant't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by acgtwentyone** [acgtwentyone/booktracks#47]
**Describe the bug**
Once the application starts load the home screen it complains and show this warning.

**To Reproduce**
1. Launch the app on an device or emulator
2. See, it complain showing the warning

**Expected behavior**
This warning should not appear

**Screenshots**
![Screen Shot 2022-06-18 at 10 27 27](https://user-images.githubusercontent.com/94224806/174435641-7e7a7f36-b94a-4e95-ada8-f6dbc031cc02.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 
 - OS: Android
 - Version: 10

**Comment by acgtwentyone** [comment]
Please, note that i am currently working on this issue

**Comment by 2002siranush** [comment]
Go to settings and click the clean button . Thank you.
